# Generated by Django 6.0.2 on 2026-02-21 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gAdministration', '0001_initial'),
        ('gCours', '0001_initial'),
        ('gEleve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note1', models.FloatField(default=0)),
                ('note2', models.FloatField(default=0)),
                ('note3', models.FloatField(default=0)),
                ('mois_evaluation', models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('janvier', 'janvier'), ('fevrier', 'fevrier'), ('mars', 'mars'), ('avril', 'avril'), ('mai', 'mai'), ('juin', 'juin'), ('juillet', 'juillet'), ('aout', 'aout'), ('septembre', 'septembre'), ('octobre', 'octobre'), ('novembre', 'novembre'), ('decembre', 'decembre')], default='Selectionnez', max_length=15)),
                ('trimestre', models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('MP', 'Maternelle/Primaire'), ('1er trimestre', '1er trimestre'), ('2ème trimestre', '2ème trimestre'), ('3ème trimestre', '3ème trimestre'), ('CLGE', 'Collège/Lycée'), ('1er semestre', '1er semestre'), ('2ème semestre', '2ème semestre')], default='Selectionnez', max_length=15)),
                ('anneescolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.anneescolaire')),
                ('idclasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.classe')),
                ('idmatiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gCours.matiere')),
                ('mateleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gEleve.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mga', models.FloatField(default=0)),
                ('annes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.anneescolaire')),
                ('idclasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.classe')),
                ('mateleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gEleve.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatTrimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimes', models.CharField(max_length=15)),
                ('mgenerale', models.FloatField(default=0)),
                ('mcours', models.FloatField(default=0)),
                ('anneescolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.anneescolaire')),
                ('idclasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.classe')),
                ('mateleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gEleve.eleve')),
            ],
        ),
    ]
