# Generated by Django 6.0.2 on 2026-02-21 12:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gAdministration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('ideleve', models.IntegerField(null=True)),
                ('matricule', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe_eleve', models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('Masculin', 'Masculin'), ('Feminin', 'Feminin')], default='Masculin', max_length=15)),
                ('pere', models.CharField(max_length=50)),
                ('mere', models.CharField(default='', max_length=50)),
                ('tuteur', models.CharField(max_length=50)),
                ('contact_parent', models.CharField(max_length=25)),
                ('adresse', models.CharField(max_length=50)),
                ('ecole_origine', models.CharField(max_length=50)),
                ('photo_eleve', models.FileField(null=True, upload_to='media/photoeleve/')),
                ('datenaissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=50)),
                ('date_arrivee', models.DateField()),
                ('date_depart', models.DateField(null=True)),
                ('depart', models.BooleanField(default=False)),
                ('pays_naissance', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif_sanction', models.TextField()),
                ('sanction', models.CharField(max_length=80)),
                ('observation', models.TextField()),
                ('date_sanction', models.DateField()),
                ('delit', models.TextField()),
                ('annescolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.anneescolaire')),
                ('idclasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.classe')),
                ('mateleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gEleve.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now=True)),
                ('etat_inscription', models.CharField(default='Inscrit', max_length=10)),
                ('regime_coran', models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('Internat', 'Internat'), ('Externat', 'Externat')], default='Internat', max_length=20)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.anneescolaire')),
                ('idclasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.classe')),
                ('idcycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gAdministration.cyclescolaire')),
                ('mateleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gEleve.eleve')),
            ],
        ),
    ]
