# Generated by Django 6.0.2 on 2026-03-25 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gEleve', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='regime_coran',
        ),
    ]
