# Generated by Django 6.0.2 on 2026-04-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gEleve', '0002_remove_inscription_regime_coran'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='email_parent',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
