# Generated by Django 6.0.2 on 2026-06-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gEleve', '0003_eleve_email_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='etat_inscription',
            field=models.CharField(choices=[('Inscrit', 'Inscrit'), ('Reinscrit', 'Reinscrit')], default='Inscrit', max_length=10),
        ),
    ]
