# Generated by Django 6.0.2 on 2026-07-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gEleve', '0004_alter_inscription_etat_inscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleve',
            old_name='contact_parent',
            new_name='contact_pere',
        ),
        migrations.RenameField(
            model_name='eleve',
            old_name='email_parent',
            new_name='email_pere',
        ),
        migrations.AddField(
            model_name='eleve',
            name='contact_mere',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='email_mere',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='personne_contact',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='profes_mere',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='profes_pere',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='mere',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='pere',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='tuteur',
            field=models.CharField(max_length=100),
        ),
    ]
