# Generated by Django 6.0.2 on 2026-08-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gEleve', '0005_rename_contact_parent_eleve_contact_pere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='sexe_eleve',
            field=models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('M', 'Masculin'), ('F', 'Feminin')], default='Masculin', max_length=15),
        ),
    ]
