# Generated by Django 6.0.2 on 2026-08-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gEleve', '0006_alter_eleve_sexe_eleve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='sexe_eleve',
            field=models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('M', 'Masculin'), ('F', 'Feminin')], default='M', max_length=15),
        ),
    ]
