# Generated by Django 6.0.2 on 2026-09-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gEleve', '0007_alter_eleve_sexe_eleve'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='mail_envoye_inscription',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
