# Generated by Django 6.0.2 on 2026-09-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gEleve', '0008_inscription_mail_envoye_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='sms_envoye_inscription',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
