# Generated by Django 6.0.2 on 2026-02-21 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript_annee', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CycleScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('Maternelle', 'Maternelle'), ('Primaire', 'Primaire'), ('Collège', 'Collège'), ('Lycée SM', 'Lycée SM'), ('Lycée SS', 'Lycée SS'), ('Lycée SE', 'Lycée SE')], default='Selectionnez', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ecole', models.CharField(max_length=50)),
                ('ville_ecole', models.CharField(max_length=20)),
                ('agrement_ecole', models.CharField(max_length=15)),
                ('prefect_commune', models.CharField(max_length=15)),
                ('bp_ecole', models.CharField(max_length=15, null=True)),
                ('telephone1', models.CharField(max_length=20)),
                ('telephone2', models.CharField(max_length=20, null=True)),
                ('email_ecole', models.EmailField(max_length=254)),
                ('site_internet', models.URLField(null=True)),
                ('devise_ecole', models.CharField(max_length=50)),
                ('logo_ecole', models.FileField(blank=True, null=True, upload_to='media/')),
                ('dsee', models.CharField(max_length=30)),
                ('dg', models.CharField(max_length=50)),
                ('coordo_primaire', models.CharField(max_length=50, null=True)),
                ('coordo_secondaire', models.CharField(blank=True, max_length=50, null=True)),
                ('comptable', models.CharField(max_length=50, null=True)),
                ('signa_dg', models.FileField(blank=True, null=True, upload_to='media/')),
                ('signa_de', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(max_length=20)),
                ('nature_operation', models.CharField(max_length=30)),
                ('detail_operation', models.TextField()),
                ('date_operation', models.DateField(auto_now=True)),
                ('heure_op', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_classe', models.CharField(max_length=20)),
                ('frais_inscription', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frais_reinscription', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frais_scolarite', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tranche1', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tranche2', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('tranche3', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('idcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.cyclescolaire')),
            ],
        ),
    ]
