# Generated by Django 6.0.2 on 2026-06-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gAdministration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='tranche2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='classe',
            name='tranche3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
