# Generated by Django 6.0.2 on 2026-07-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gAdministration', '0002_alter_classe_tranche2_alter_classe_tranche3'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='coordo_maternelle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ecole',
            name='dga',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historique',
            name='email_user',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historique',
            name='poste_travail',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
