# Generated by Django 6.0.2 on 2026-07-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gAdministration', '0003_ecole_coordo_maternelle_ecole_dga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='user_login',
            field=models.CharField(max_length=50),
        ),
    ]
