# Generated by Django 6.0.2 on 2026-08-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gAdministration', '0004_alter_historique_user_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='delai_reinscription',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ecole',
            name='delai_tranche1',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ecole',
            name='delai_tranche2',
            field=models.DateField(null=True),
        ),
    ]
