# Generated by Django 6.0.2 on 2026-09-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gAdministration', '0005_ecole_delai_reinscription_ecole_delai_tranche1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='frais_inscription',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='classe',
            name='frais_reinscription',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
