# Generated by Django 6.0.2 on 2026-02-21 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gAdministration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_personnel', models.CharField(max_length=30)),
                ('prenom_personnel', models.CharField(max_length=50)),
                ('civilite', models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('Monsieur', 'Monsieur'), ('Madame', 'Madame'), ('Madémoiselle', 'Madémoisselle')], default='Selectionnez', max_length=15)),
                ('date_naissance', models.DateField()),
                ('niveau_etude', models.CharField(max_length=50)),
                ('type_personnel', models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('Vacataire', 'Vacataire'), ('Permanent', 'Permanent')], default='Selectionnez', max_length=15)),
                ('adresse_personnel', models.CharField(max_length=50)),
                ('contact_personnel', models.CharField(max_length=25)),
                ('fonction_personnel', models.CharField(max_length=35)),
                ('email_personnel', models.EmailField(max_length=254)),
                ('sexe_personnel', models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('Homme', 'Homme'), ('Femme', 'Femme')], default='Selectionnez', max_length=15)),
                ('salbase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annee_experience', models.CharField(max_length=10)),
                ('contrat_type', models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('CDD', 'CDD'), ('CDI', 'CDI')], default='Selectionnez', max_length=15)),
                ('diplome', models.CharField(max_length=25)),
                ('date_embauche', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ContratTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(auto_now=True)),
                ('date_fin', models.DateField(auto_now=True)),
                ('periode_essai', models.CharField(max_length=10)),
                ('thoraire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salfixe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree_contrat_chiffre', models.IntegerField(default=1)),
                ('duree_contrat_lettre', models.CharField(max_length=50)),
                ('date_signature_contrat', models.DateField(auto_now=True)),
                ('idpersonnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gPersonnel.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='AvanceSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_avance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('intitule', models.TextField()),
                ('date_avance', models.DateField(auto_now=True)),
                ('mois_avance', models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('janvier', 'janvier'), ('fevrier', 'fevrier'), ('mars', 'mars'), ('avril', 'avril'), ('mai', 'mai'), ('juin', 'juin'), ('juillet', 'juillet'), ('aout', 'aout'), ('septembre', 'septembre'), ('octobre', 'octobre'), ('novembre', 'novembre'), ('decembre', 'decembre')], default='Selectionnez', max_length=15)),
                ('anscolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.anneescolaire')),
                ('idpersonnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gPersonnel.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(auto_now=True)),
                ('nbre_heure', models.IntegerField(default=0)),
                ('mois_paie', models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('janvier', 'janvier'), ('fevrier', 'fevrier'), ('mars', 'mars'), ('avril', 'avril'), ('mai', 'mai'), ('juin', 'juin'), ('juillet', 'juillet'), ('aout', 'aout'), ('septembre', 'septembre'), ('octobre', 'octobre'), ('novembre', 'novembre'), ('decembre', 'decembre')], default='Selectionnez', max_length=15)),
                ('detail_paiement', models.TextField()),
                ('taux_horaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avance_paie', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('primes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salbrut', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cotis_sociale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salnet', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nb_hsupp', models.IntegerField(default=0)),
                ('mont_hsupp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('anneescolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.anneescolaire')),
                ('idpersonnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gPersonnel.personnel')),
            ],
        ),
    ]
