# Generated by Django 6.0.2 on 2026-07-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gPersonnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancesalaire',
            name='mois_avance',
            field=models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('janvier', 'janvier'), ('fevrier', 'fevrier'), ('mars', 'mars'), ('avril', 'avril'), ('mai', 'mai'), ('juin', 'juin'), ('juillet', 'juillet'), ('aout', 'août'), ('septembre', 'septembre'), ('octobre', 'octobre'), ('novembre', 'novembre'), ('decembre', 'décembre')], default='Selectionnez', max_length=15),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='mois_paie',
            field=models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('janvier', 'janvier'), ('fevrier', 'fevrier'), ('mars', 'mars'), ('avril', 'avril'), ('mai', 'mai'), ('juin', 'juin'), ('juillet', 'juillet'), ('aout', 'août'), ('septembre', 'septembre'), ('octobre', 'octobre'), ('novembre', 'novembre'), ('decembre', 'décembre')], default='Selectionnez', max_length=15),
        ),
    ]
