# Generated by Django 6.0.2 on 2026-08-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gPersonnel', '0002_alter_avancesalaire_mois_avance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancesalaire',
            name='mois_avance',
            field=models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('janvier', 'janvier'), ('fevrier', 'fevrier'), ('mars', 'mars'), ('avril', 'avril'), ('mai', 'mai'), ('juin', 'juin'), ('juillet', 'juillet'), ('aout', 'août'), ('septembre', 'septembre'), ('octobre', 'octobre'), ('novembre', 'novembre'), ('decembre', 'décembre')], default='janvier', max_length=15),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='civilite',
            field=models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('M', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Madémoisselle')], default='M', max_length=15),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='contrat_type',
            field=models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('CDD', 'CDD'), ('CDI', 'CDI')], default='CDD', max_length=15),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='sexe_personnel',
            field=models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('H', 'Homme'), ('F', 'Femme')], default='H', max_length=15),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='type_personnel',
            field=models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('Vacataire', 'Vacataire'), ('Permanent', 'Permanent')], default='Vacataire', max_length=15),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='mois_paie',
            field=models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('janvier', 'janvier'), ('fevrier', 'fevrier'), ('mars', 'mars'), ('avril', 'avril'), ('mai', 'mai'), ('juin', 'juin'), ('juillet', 'juillet'), ('aout', 'août'), ('septembre', 'septembre'), ('octobre', 'octobre'), ('novembre', 'novembre'), ('decembre', 'décembre')], default='janvier', max_length=15),
        ),
    ]
