# Generated by Django 6.0.2 on 2026-09-18 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gAdministration', '0006_alter_classe_frais_inscription_and_more'),
        ('gPersonnel', '0003_alter_avancesalaire_mois_avance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrattravail',
            name='aneescolaire',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='gAdministration.anneescolaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel',
            name='annee_scolaire',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='gAdministration.anneescolaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel',
            name='etat_matrimonial',
            field=models.CharField(choices=[('Celibatiare', 'Célibataire'), ('Marie', 'Marié(e)'), ('Divorce', 'Divorcé(e)'), ('Veuf', 'Veuf(ve)')], default='Celibatiare', max_length=50),
        ),
        migrations.AddField(
            model_name='personnel',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='photo_employe',
            field=models.FileField(blank=True, null=True, upload_to='media/photoemploye/'),
        ),
        migrations.AlterField(
            model_name='avancesalaire',
            name='montant_avance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='contrattravail',
            name='date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contrattravail',
            name='date_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contrattravail',
            name='date_signature_contrat',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contrattravail',
            name='salfixe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='contrattravail',
            name='thoraire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='adresse_personnel',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='annee_experience',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='civilite',
            field=models.CharField(choices=[('M', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Madémoisselle')], default='M', max_length=15),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='contrat_type',
            field=models.CharField(choices=[('CDD', 'Contrat Durée Déterminée-CDD'), ('CDI', 'Contrat Durée Indéterminée-CDI')], default='CDD', max_length=15),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='date_embauche',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='date_naissance',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='diplome',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='email_personnel',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='fonction_personnel',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='niveau_etude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='nom_personnel',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='prenom_personnel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='salbase',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='sexe_personnel',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default='H', max_length=15),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='type_personnel',
            field=models.CharField(choices=[('Vacataire', 'Vacataire'), ('Permanent', 'Permanent')], default='Vacataire', max_length=15),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='date_paiement',
            field=models.DateField(),
        ),
    ]
