# Generated by Django 6.0.2 on 2026-09-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gPersonnel', '0004_contrattravail_aneescolaire_personnel_annee_scolaire_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContratTravail',
        ),
    ]
