# Generated by Django 6.0.2 on 2026-09-19 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gAdministration', '0006_alter_classe_frais_inscription_and_more'),
        ('gPersonnel', '0005_delete_contrattravail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('periode_essai', models.CharField(max_length=10)),
                ('thoraire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salfixe', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('duree_contrat_chiffre', models.IntegerField(default=1)),
                ('duree_contrat_lettre', models.CharField(max_length=50)),
                ('date_signature_contrat', models.DateField()),
                ('aneescolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.anneescolaire')),
                ('idpersonnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gPersonnel.personnel')),
            ],
        ),
    ]
