# Generated by Django 6.0.2 on 2026-09-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gPersonnel', '0006_contrattravail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancesalaire',
            name='date_avance',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='contrat_type',
            field=models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI')], default='CDD', max_length=15),
        ),
    ]
