# Generated by Django 6.0.2 on 2026-10-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gPersonnel', '0007_alter_avancesalaire_date_avance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancesalaire',
            name='intitule',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='avancesalaire',
            name='mois_avance',
            field=models.CharField(choices=[('Selectionnez', 'Sélectionnez'), (1, 'janvier'), (2, 'fevrier'), (3, 'mars'), (4, 'avril'), (5, 'mai'), (6, 'juin'), (7, 'juillet'), (8, 'août'), (9, 'septembre'), (10, 'octobre'), (11, 'novembre'), (12, 'décembre')], default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='mois_paie',
            field=models.CharField(choices=[('Selectionnez', 'Sélectionnez'), (1, 'janvier'), (2, 'fevrier'), (3, 'mars'), (4, 'avril'), (5, 'mai'), (6, 'juin'), (7, 'juillet'), (8, 'août'), (9, 'septembre'), (10, 'octobre'), (11, 'novembre'), (12, 'décembre')], default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='salbrut',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='salnet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
