# Generated by Django 6.0.2 on 2026-10-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gPersonnel', '0008_alter_avancesalaire_intitule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancesalaire',
            name='mois_avance',
            field=models.CharField(choices=[('', 'Sélectionnez'), (1, 'janvier'), (2, 'fevrier'), (3, 'mars'), (4, 'avril'), (5, 'mai'), (6, 'juin'), (7, 'juillet'), (8, 'août'), (9, 'septembre'), (10, 'octobre'), (11, 'novembre'), (12, 'décembre')], default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='mois_paie',
            field=models.CharField(choices=[('', 'Sélectionnez'), (1, 'janvier'), (2, 'fevrier'), (3, 'mars'), (4, 'avril'), (5, 'mai'), (6, 'juin'), (7, 'juillet'), (8, 'août'), (9, 'septembre'), (10, 'octobre'), (11, 'novembre'), (12, 'décembre')], default=1, max_length=15),
        ),
    ]
