# Generated by Django 6.0.2 on 2026-02-21 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gAdministration', '0001_initial'),
        ('gPersonnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.CharField(max_length=50)),
                ('coeff', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbre_heure_cour', models.IntegerField()),
                ('jour', models.CharField(max_length=10)),
                ('heure_debut', models.TimeField(auto_now=True)),
                ('heure_fin', models.TimeField(auto_now=True)),
                ('idpersonnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gPersonnel.personnel')),
                ('idmatiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gCours.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbre_heure_absence', models.IntegerField()),
                ('motif_absence', models.CharField(max_length=50)),
                ('type_motif', models.CharField(max_length=20)),
                ('date_absence', models.DateField()),
                ('mois_absence', models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('janvier', 'janvier'), ('fevrier', 'fevrier'), ('mars', 'mars'), ('avril', 'avril'), ('mai', 'mai'), ('juin', 'juin'), ('juillet', 'juillet'), ('aout', 'aout'), ('septembre', 'septembre'), ('octobre', 'octobre'), ('novembre', 'novembre'), ('decembre', 'decembre')], default='Selectionnez', max_length=15)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.anneescolaire')),
                ('idcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gCours.cours')),
            ],
        ),
    ]
