# Generated by Django 6.0.2 on 2026-10-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gCours', '0002_alter_absence_mois_absence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='mois_absence',
            field=models.CharField(choices=[('Selectionnez', 'Sélectionnez'), (1, 'janvier'), (2, 'fevrier'), (3, 'mars'), (4, 'avril'), (5, 'mai'), (6, 'juin'), (7, 'juillet'), (8, 'août'), (9, 'septembre'), (10, 'octobre'), (11, 'novembre'), (12, 'décembre')], default='Selectionnez', max_length=15),
        ),
    ]
