# Generated by Django 6.0.2 on 2026-08-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.FileField(blank=True, null=True, upload_to='media/photos_profil/'),
        ),
    ]
