# Generated by Django 6.0.2 on 2026-08-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gUsers', '0002_alter_utilisateur_photo_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='niveau_acces',
            field=models.CharField(choices=[('DG', 'Directeur Général'), ('SCOL', 'Service Scolarité'), ('COMPTA', 'Comptable'), ('ENS', 'Enseignant')], default='DG', max_length=10),
        ),
    ]
