# Generated by Django 6.0.2 on 2026-09-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gUsers', '0003_alter_utilisateur_niveau_acces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='niveau_acces',
            field=models.CharField(choices=[('DG', 'Directeur Général'), ('DE', 'Directeur des Etudes'), ('SCOL', 'Service Scolarité'), ('COMPTA', 'Comptable'), ('ENS', 'Enseignant')], default='DG', max_length=10),
        ),
    ]
