# Generated by Django 6.0.2 on 2026-07-23 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gAdministration', '0004_alter_historique_user_login'),
        ('gEleve', '0005_rename_contact_parent_eleve_contact_pere_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_operation', models.TextField()),
                ('montant_encaisse', models.DecimalField(decimal_places=2, max_digits=20)),
                ('type_operation', models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('Recette', 'Recette'), ('Dépense', 'Dépense')], default='Selectionnez', max_length=15)),
                ('date_operation', models.DateField(null=True)),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('heure_operation', models.TimeField(auto_now=True)),
                ('qte', models.IntegerField(default=0, null=True)),
                ('pua', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('provient', models.CharField(max_length=50, null=True)),
                ('destine', models.CharField(max_length=50, null=True)),
                ('observ', models.CharField(max_length=90, null=True)),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='media/')),
                ('categ_depense', models.CharField(default='Selectionnez', max_length=100)),
                ('anscolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.anneescolaire')),
            ],
        ),
        migrations.CreateModel(
            name='EtatPaiementTranche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('m_rabais', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('premiere_tranche', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('deuxieme_tranche', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('troisieme_tranche', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fscolarite', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('reste_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('date_paie', models.DateField()),
                ('anneescolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.anneescolaire')),
                ('idclasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.classe')),
                ('idcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.cyclescolaire')),
                ('mateleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gEleve.eleve')),
            ],
        ),
    ]
