# Generated by Django 6.0.2 on 2026-02-21 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gAdministration', '0001_initial'),
        ('gEleve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_operation', models.TextField()),
                ('montant_encaisse', models.DecimalField(decimal_places=2, max_digits=20)),
                ('type_operation', models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('Recette', 'Recette'), ('Dépense', 'Dépense')], default='Selectionnez', max_length=15)),
                ('date_operation', models.DateField(auto_now=True)),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('heure_operation', models.TimeField(auto_now=True)),
                ('qte', models.IntegerField(default=0, null=True)),
                ('pua', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('provient', models.CharField(max_length=50, null=True)),
                ('destine', models.CharField(max_length=50, null=True)),
                ('observ', models.CharField(max_length=90, null=True)),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='media/')),
                ('categ_depense', models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('Salaires', 'Salaires'), ('Charges locatives', 'Charges locatives'), ('Mobiliers et Infrastructures', 'Mobiliers et Infrastructures'), ('Fournitures Scolaires', 'Fournitures scolaires et de Bureau'), ('Autres Fournitures', 'Autres fournitures'), ('Investissements', 'Investissements'), ('Amortissements', 'Amortissements'), ('Charges Recurrentes', 'Charges récurrentes'), ('Créances', 'Créances'), ('Dettes', 'Dettes'), ('Autres Charges', 'Autres charges'), ('Scolarité', 'Scolarité'), ('Cours Revision', 'Cours révision'), ('Cours Coraniques', 'Cours coraniques'), ('Arriere Scolaire', 'Arriere scolaire'), ('Remboursement Prêt', 'Remboursement prêt'), ('Divers', 'Divers'), ('Autres Recettes', 'Autres recettes')], default='Selectionnez', max_length=100)),
                ('anscolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.anneescolaire')),
            ],
        ),
        migrations.CreateModel(
            name='EtatPaiementCoran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('m_rabais', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fjanvier', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('ffevreir', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fmars', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('favril', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fmai', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fjuin', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fjuillet', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('faout', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fseptembre', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fnovembre', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fdecembre', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('anneescolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.anneescolaire')),
                ('idclasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.classe')),
                ('mateleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gEleve.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='EtatPaiementRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('m_rabais', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fjanvier', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('ffevreir', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fmars', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('favril', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fmai', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fjuin', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fjuillet', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('faout', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fseptembre', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fnovembre', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fdecembre', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('anneescolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.anneescolaire')),
                ('idclasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.classe')),
                ('mateleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gEleve.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='EtatPaiementScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('m_rabais', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fjanvier', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('ffevreir', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fmars', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('favril', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fmai', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fjuin', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fjuillet', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('faout', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fseptembre', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fnovembre', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fdecembre', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('anneescolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.anneescolaire')),
                ('idclasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.classe')),
                ('mateleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gEleve.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementCoran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_paye', models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('janvier', 'janvier'), ('fevrier', 'fevrier'), ('mars', 'mars'), ('avril', 'avril'), ('mai', 'mai'), ('juin', 'juin'), ('juillet', 'juillet'), ('aout', 'aout'), ('septembre', 'septembre'), ('octobre', 'octobre'), ('novembre', 'novembre'), ('decembre', 'decembre')], default='Selectionnez', max_length=15)),
                ('date_payement', models.DateField(auto_now=True)),
                ('detail', models.TextField()),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mont_du', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reste_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('anneescolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.anneescolaire')),
                ('idclasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.classe')),
                ('mateleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gEleve.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_paye', models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('janvier', 'janvier'), ('fevrier', 'fevrier'), ('mars', 'mars'), ('avril', 'avril'), ('mai', 'mai'), ('juin', 'juin'), ('juillet', 'juillet'), ('aout', 'aout'), ('septembre', 'septembre'), ('octobre', 'octobre'), ('novembre', 'novembre'), ('decembre', 'decembre')], default='Selectionnez', max_length=15)),
                ('date_payement', models.DateField(auto_now=True)),
                ('detail', models.TextField()),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mont_du', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reste_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('anneescolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.anneescolaire')),
                ('idclasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.classe')),
                ('mateleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gEleve.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_paye', models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('janvier', 'janvier'), ('fevrier', 'fevrier'), ('mars', 'mars'), ('avril', 'avril'), ('mai', 'mai'), ('juin', 'juin'), ('juillet', 'juillet'), ('aout', 'aout'), ('septembre', 'septembre'), ('octobre', 'octobre'), ('novembre', 'novembre'), ('decembre', 'decembre')], default='Selectionnez', max_length=15)),
                ('date_payement', models.DateField(auto_now=True)),
                ('detail', models.TextField()),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mont_du', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reste_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tranche_paye', models.CharField(max_length=25)),
                ('anneescolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.anneescolaire')),
                ('idclasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.classe')),
                ('mateleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gEleve.eleve')),
            ],
        ),
    ]
