# Generated by Django 6.0.2 on 2026-08-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gComptabilite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatpaiementtranche',
            name='mode_paie',
            field=models.CharField(choices=[('Espèce', 'Espèce'), ('Chèque', 'Chèque'), ('Virement bancaire', 'Virement bancaire'), ('Orange Money', 'Orange Money'), ('MTN Mobile Money', 'MTN Mobile Money')], default='Espèce', max_length=50, null=True),
        ),
    ]
