# Generated by Django 6.0.2 on 2026-03-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gComptabilite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='categ_depense',
            field=models.CharField(default='Selectionnez', max_length=100),
        ),
    ]
