# Generated by Django 6.0.2 on 2026-06-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gComptabilite', '0002_alter_caisse_categ_depense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='date_operation',
            field=models.DateField(),
        ),
    ]
