# Generated by Django 6.0.2 on 2026-08-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gComptabilite', '0002_etatpaiementtranche_mode_paie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='type_operation',
            field=models.CharField(choices=[('Selectionnez', 'Sélectionnez'), ('Recette', 'Recette'), ('Dépense', 'Dépense')], default='Recette', max_length=15),
        ),
    ]
