# Generated by Django 6.0.2 on 2026-06-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gComptabilite', '0003_alter_caisse_date_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='date_operation',
            field=models.DateField(null=True),
        ),
    ]
