# Generated by Django 6.0.2 on 2026-09-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gComptabilite', '0003_alter_caisse_type_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='pua',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='solde_actuel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='etatpaiementtranche',
            name='deuxieme_tranche',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='etatpaiementtranche',
            name='fscolarite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='etatpaiementtranche',
            name='inscription',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='etatpaiementtranche',
            name='m_rabais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='etatpaiementtranche',
            name='premiere_tranche',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='etatpaiementtranche',
            name='reste_a_payer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='etatpaiementtranche',
            name='troisieme_tranche',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
