# Generated by Django 6.0.2 on 2026-07-10 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gAdministration', '0003_ecole_coordo_maternelle_ecole_dga_and_more'),
        ('gComptabilite', '0004_alter_caisse_date_operation'),
        ('gEleve', '0005_rename_contact_parent_eleve_contact_pere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etatpaiementrevision',
            name='anneescolaire',
        ),
        migrations.RemoveField(
            model_name='etatpaiementrevision',
            name='idclasse',
        ),
        migrations.RemoveField(
            model_name='etatpaiementrevision',
            name='mateleve',
        ),
        migrations.RemoveField(
            model_name='etatpaiementscolarite',
            name='anneescolaire',
        ),
        migrations.RemoveField(
            model_name='etatpaiementscolarite',
            name='idclasse',
        ),
        migrations.RemoveField(
            model_name='etatpaiementscolarite',
            name='mateleve',
        ),
        migrations.RemoveField(
            model_name='paiementcoran',
            name='anneescolaire',
        ),
        migrations.RemoveField(
            model_name='paiementcoran',
            name='idclasse',
        ),
        migrations.RemoveField(
            model_name='paiementcoran',
            name='mateleve',
        ),
        migrations.RemoveField(
            model_name='paiementrevision',
            name='anneescolaire',
        ),
        migrations.RemoveField(
            model_name='paiementrevision',
            name='idclasse',
        ),
        migrations.RemoveField(
            model_name='paiementrevision',
            name='mateleve',
        ),
        migrations.RemoveField(
            model_name='paiementscolarite',
            name='anneescolaire',
        ),
        migrations.RemoveField(
            model_name='paiementscolarite',
            name='idclasse',
        ),
        migrations.RemoveField(
            model_name='paiementscolarite',
            name='mateleve',
        ),
        migrations.CreateModel(
            name='EtatPaiementTranche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('m_rabais', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('premiere_tranche', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('deuxieme_tranche', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('troisieme_tranche', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('fscolarite', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('reste_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('date_paie', models.DateField()),
                ('anneescolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.anneescolaire')),
                ('idclasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gAdministration.classe')),
                ('mateleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gEleve.eleve')),
            ],
        ),
        migrations.DeleteModel(
            name='EtatPaiementCoran',
        ),
        migrations.DeleteModel(
            name='EtatPaiementRevision',
        ),
        migrations.DeleteModel(
            name='EtatPaiementScolarite',
        ),
        migrations.DeleteModel(
            name='PaiementCoran',
        ),
        migrations.DeleteModel(
            name='PaiementRevision',
        ),
        migrations.DeleteModel(
            name='PaiementScolarite',
        ),
    ]
