# Generated by Django 6.0.2 on 2026-09-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gComptabilite', '0004_alter_caisse_pua_alter_caisse_solde_actuel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatpaiementtranche',
            name='mail_envoye_paie',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
