# Generated by Django 6.0.2 on 2026-09-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gComptabilite', '0005_etatpaiementtranche_mail_envoye_paie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etatpaiementtranche',
            old_name='mail_envoye_paie',
            new_name='mail_envoye_paie_pt',
        ),
        migrations.AddField(
            model_name='etatpaiementtranche',
            name='mail_envoye_paie_dt',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
