# Generated by Django 6.0.2 on 2026-09-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gComptabilite', '0006_rename_mail_envoye_paie_etatpaiementtranche_mail_envoye_paie_pt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatpaiementtranche',
            name='sms_envoye_paie_dt',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='etatpaiementtranche',
            name='sms_envoye_paie_pt',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
