from django.contrib import admin
from .models import *
admin.site.register(CycleScolaire)
admin.site.register(Classe)
admin.site.register(Eleve)
admin.site.register(Personnel)
admin.site.register(Matiere)
admin.site.register(AnneeScolaire)
admin.site.register(Cours)
admin.site.register(Ecole)
admin.site.register(Absence)
admin.site.register(AvanceSalaire)
admin.site.register(Caisse)
admin.site.register(ContratTravail)
admin.site.register(Discipline)
admin.site.register(EtatPaiementCoran)
admin.site.register(EtatPaiementRevision)
admin.site.register(EtatPaiementScolarite)
admin.site.register(Evaluation)
admin.site.register(Historique)
admin.site.register(Inscription)
admin.site.register(PaiementCoran)
admin.site.register(PaiementRevision)
admin.site.register(PaiementScolarite)
admin.site.register(Salaire)
admin.site.register(ResultatAnnuel)
admin.site.register(ResultatTrimestre)

