# Django settings for stsavenirafrique project.
#
# Generated by 'django-admin startproject' using Django 6.0
#
# For more information on this file, see
# https://docs.djangoproject.com/en/4.2/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/4.2/ref/settings/

from decouple import config
from pathlib import Path
import os
from django.contrib.messages import constants as messages


# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = Path(__file__).resolve().parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Application definition

INSTALLED_APPS = [
    'adminlte3',
    'adminlte3_theme',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gAdministration',
    'gComptabilite',
    'gCours',
    'gEleve',
    'gNotes',
    'gPersonnel',
    'gUsers',
    'crispy_forms',
    'fontawesomefree',
    'core', # C'est l'application partagee contenant les fonctions d'envoi des emails groupes et d'autres fonctions partagees
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Messages TAGS
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger'
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stsavenirafrique.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processor.annee_scolaire_actuelle', # Peut être affiché dans tous les templates du projet
                'core.context_processor.afficher_logoEcole', # Permet d'afficher le logo de l'école dans tous les templates
            ],
        },
    },
]

WSGI_APPLICATION = 'stsavenirafrique.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DB_ENGINE = config('DB_ENGINE', default='postgresql')
ENV = config('ENVIRONMENT', default='local')

if ENV == 'test':
    DB_ENGINE = 'mysql'
    DB_NAME = config('DB_NAME_TEST')
    DB_USER = config('DB_USER_TEST')
    DB_PASSWORD = config('DB_PASSWORD_TEST')
    DB_HOST = config('DB_HOST_TEST', default='localhost')
    DB_PORT = config('DB_PORT_TEST', default='3306')
elif ENV == 'prod':
    DB_ENGINE = 'mysql'
    DB_NAME = config('DB_NAME_PROD')
    DB_USER = config('DB_USER_PROD')
    DB_PASSWORD = config('DB_PASSWORD_PROD')
    DB_HOST = config('DB_HOST_PROD', default='localhost')
    DB_PORT = config('DB_PORT_PROD', default='3306')
else:  # local
    DB_ENGINE = 'postgresql'
    DB_NAME = config('DB_NAME')
    DB_USER = config('DB_USER')
    DB_PASSWORD = config('DB_PASSWORD')
    DB_HOST = config('DB_HOST', default='localhost')
    DB_PORT = config('DB_PORT', default='5432')

DATABASES = {
    'default': {
        'ENGINE': f'django.db.backends.{DB_ENGINE}',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
        'OPTIONS': {'charset': 'utf8mb4', 'init_command': "SET sql_mode='STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,STRICT_ALL_TABLES'"} if DB_ENGINE == 'mysql' else {},
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_ROOT = os.path.normpath(os.path.join(BASE_DIR, 'staticfiles'))
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# MEDIA_DIR = BASE_DIR/'media'

MEDIA_DIR = os.path.join(BASE_DIR, 'media')
MEDIA_ROOT = MEDIA_DIR
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Format par defaut des champs de type date
DATE_INPUT_FORMATS = ['%d-%m-%Y', '%Y-%m-%d', '%m-%d-%Y']
DATE_FORMAT = 'j N, Y'

# Déclare le nouveau modèle utilisateur au projet
AUTH_USER_MODEL = 'gUsers.Utilisateur'

LOGIN_REDIRECT_URL = 'accueil'
LOGIN_URL = '/'  # C'est l'URL de la page de connexion
LOGOUT_REDIRECT_URL = '/'
LOGOUT_URL = '/'

# Durée de validité du lien de réinitialisation de mot de passe (1h)
PASSWORD_RESET_TIMEOUT = 3600

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = f"GS Ecole les Champions <{config('EMAIL_HOST_USER')}>"

# À la fin de votre fichier settings.py

if not DEBUG:
    # Configuration de sécurité pour la production
    ALLOWED_HOSTS = [
    'school-tech-solution.universtechgroup.com',
    'www.school-tech-solution.universtechgroup.com',
    'ecole-les-champions.universtechgroup.com',
    'www.ecole-les-champions.universtechgroup.com',
]   
    # Prévient la boucle infinie de redirections sur o2switch 🔑
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    # Configuration pour le développement local
    ALLOWED_HOSTS = [
        'localhost',
        '127.0.0.1',
        'school-tech-solution.universtechgroup.com',
        'www.school-tech-solution.universtechgroup.com',
    ]
    # config('ALLOWED_HOSTS',default='localhost,127.0.0.1', 
    #        cast=lambda v: [h.strip() for h in v.split(',')]
    #     )

